version: "3"
services: 
    app:
        build: docker/app
        tty: true
        volumes: 
            - ./app:/app 
        ports: 
            - "3000:3000"
        user: node 
        command: yarn start